### ISSUE TITLE
error when executing delete_cluster script

### ISSUE THREAD

**Issue by senpot** [aws/eks-distro#115]
**What happened**:
After I executed `delete_cluster.sh` then the error message `error removing cluster from state store: refusing to delete: unknown file found: s3://<KOPS_STATE_STORE>/<KOPS_CLUSTER_NAME>/config` appeared on the console.

So I executed `delete_store.sh`, and S3 bucket is deleted.
Do I need to execute `delete_store.sh` after executing `delete_cluster.sh`?

If I need to execute `delete_store.sh`, I suggest to add `delete_store.sh` following page.
[EKS Distro kOps Cluster:kOps Cluster Delete](https://github.com/aws/eks-distro/blob/main/development/kops/README.md#kops-cluster-delete)

**Comment by TerryHowe** [comment]
I have one thing I wanted to investigate that *may* be related to this. The reason the delete store script is not mentioned in the README is because some people may want to reuse their s3 bucket and they may have multiple clusters on a single bucket. The delete store script is what is used for the automated tests.

**Comment by TerryHowe** [comment]
I tried to reproduce this problem with the code from #92 and I'm not seeing it. I know I've seen this problem before and I think the change to the template where the cluster name was fixed solves this problem. This will close when that merges.

**Comment by TerryHowe** [comment]
That merge of #92 should resolve this problem.
