### ISSUE TITLE
Error while creating cluster | tags/v1-23-eks-5

### ISSUE THREAD

**Issue by jeenadeepak** [aws/eks-distro#1245]
**What happened**:

[ec2-user@ip-172-31-3-34 kops]$ ./create_cluster.sh 
✔ AWS_REGION=me-south-1
✔ AWS CLI authenticated
✔ KOPS_STATE_STORE=s3://h-kops-state-store
✔ KOPS_CLUSTER_NAME=ex-test-eks.test.co
Error: error building complete spec: error reading tag file "https://distro.eks.amazonaws.com/kubernetes-1-23/releases/7/artifacts/kubernetes/v1.23.9/bin/linux/amd64/kube-apiserver.docker_tag": unexpected response code "403 Forbidden" for "https://distro.eks.amazonaws.com/kubernetes-1-23/releases/7/artifacts/kubernetes/v1.23.9/bin/linux/amd64/kube-apiserver.docker_tag": <?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>J7N3NHS1S30H31MQ</RequestId><HostId>T+VNCMcZ/XHdwcSzvVwO2SSnnH6b14FEmfhlt/gOc7MUXAjB/LoweuWQmkK6q1AMdX4ibmIC1zk=</HostId></Error>

**What you expected to happen**:
Cluster should be created.

**How to reproduce it (as minimally and precisely as possible)**:

Checkout tag: v1-23-eks-5

Follow: https://distro.eks.amazonaws.com/users/install/kops/

**Anything else we need to know?**:

**Environment**:
- EKS Distro Release Channel:
- EKS Distro Release: v1-23-eks-5

**Comment by markapruett** [comment]
Thanks for submitting this @jeenadeepak. 

The default value for [RELEASE_ENVIRONMENT](https://github.com/aws/eks-distro/blob/a7dec5484c2c41931582f5c19fecd68ad3d62552/development/kops/set_environment.sh#L19) is set to `development`, which results in it trying to pull the artifacts at 7 which is [latest dev release](https://github.com/aws/eks-distro/tree/main/release/1-23/development). It fails because those don't exist for production.  

Before running the kOps script, try setting RELEASE_ENVIRONMENT to `production` and it should reference 1.23-5 as expected.

**Comment by markapruett** [comment]
Closing this out. If you still run into trouble we can reopen it.
