### ISSUE TITLE
Fix broken changelog links in release announcements

### ISSUE THREAD

**Issue by markapruett** [aws/eks-distro#1248]
The changelog links go to a 404. Correct these to link to the files correctly. Example: https://github.com/aws/eks-distro/releases

We want to remove the For additional information, see the changelog for this release. line from the releases page BUT keep it on the index.md for the release ([example](https://github.com/aws/eks-distro/blob/main/docs/contents/releases/1-23/5/index.md))

**Comment by dublinsubway** [comment]
Hiya. I can work on this, but since it might entail giving me too much access - that's fine if I can't Links for reference:

https://distro.eks.amazonaws.com/releases/1-23/5/CHANGELOG-v1-23-eks-5 - docs site link

https://github.com/aws/eks-distro/blob/v1-23-eks-5/CHANGELOG-v1-23-eks-5.md - broken link from announcements
 
https://github.com/aws/eks-distro/blob/main/docs/contents/releases/1-23/5/CHANGELOG-v1-23-eks-5.md - working link

**Comment by markapruett** [comment]
Thanks @dublinsubway! You should be able to see everything you need to make these changes in the EKS-D repo.

**Comment by kschumy** [comment]
We want to remove the `For additional information, see the changelog for this release.` line from the releases page BUT keep it on the index.md for the release ([example](https://github.com/aws/eks-distro/blob/main/docs/contents/releases/1-23/5/index.md))

**Comment by markapruett** [comment]
@zafs23 @kschumy Can this ticket be closed out?

**Comment by zafs23** [comment]
After releasing all the github release docs will close this ticket
