### ISSUE TITLE
Invalid prerelease Semantic Version string used by EKS

### ISSUE THREAD

**Issue by smlx** [aws/eks-distro#512]
**What happened**:

I tried to install a Helm chart into EKS which had a version requirement like:
```
kubeVersion: ">= 1.19.0"
```

This returned an error:
```
  Error: chart requires kubeVersion: >= 1.19.0 which is incompatible with Kubernetes v1.20.7-eks-d88609
```

**What you expected to happen**:

I expected the chart to install since the kubernetes version is nominally supported.

**How to reproduce it (as minimally and precisely as possible)**:

```
$ helm create foo
Creating foo
$ echo 'kubeVersion: ">= 1.19.0"' >> foo/Chart.yaml
$ helm --kube-version=1.20.0-eks-123 template foo
Error: chart requires kubeVersion: >= 1.19.0 which is incompatible with Kubernetes v1.20.0-eks-123

Use --debug flag to render out invalid YAML
```

**Anything else we need to know?**:

The problem is that the practice of appending `-eks-*` to the version returned by the kubernetes API is not correct according to Semantic Versioning. A hyphen-appended suffix indicates a prerelease version. For build metadata like the `eks` suffix on a production release version, a `+` should be used: `1.20.0+eks-123`. See SemVer spec items [9 and 10](https://semver.org/#spec-item-9).

Demonstrating that this works using the test case above:
```
$ helm --kube-version=1.20.0+eks-123 template foo
...
```

There is further discussion here: https://github.com/helm/helm/issues/3810

**Environment**:
- EKS Distro Release Channel: n/a
- EKS Distro Release: v1.20.7-eks-d88609

**Comment by TerryHowe** [comment]
Interesting, thanks.

**Comment by jaxesn** [comment]
We spoke with the EKS team about this and it has been discussed a few times before and it's ultimately not a change they want to make. Since we want to keep versioning in sync between eks distro and eks we will not make a change here either.

The helm workaround you referenced in your linked PR seems to be the community's agreed upon way to work around this kind of versioning, which other kubernetes vendors also follow.

Closing this out for now, but will def reopen/update if there are other conversations that come up.

**Comment by smlx** [comment]
Thanks for the response and explanation.

> which other kubernetes vendors also follow.

As far as I'm aware only GKE has the same bug. Kubernetes distros I've checked that do versioning correctly include AKS, kind, k3s and Openshift.
