### ISSUE TITLE
Use kops default coredns config

### ISSUE THREAD

**Issue by olemarkus** [aws/eks-distro#64]
The kops.sh script currently sets an external coredns config file. This file is more or less equivalent to kops 1.19 default.
I suspect this is because kops prior to 1.19 set `upstream`. But since 1.19 features (metrics server addon) is used anyway, it is probably better to just rely on kops doing the right thing.

Relying on kops to configure coredns correctly will also ensure users automatically receives future changes automatically rather than manually apply the changes in the cluster spec.

**Comment by jaxesn** [comment]
Thanks for your comment!  You are right, that override exist to support coredns 1.7.0 which kops 1.19 does support.  Since kops 1.19 was/is still in beta we figured having the override for now will be the least disruptive to those still using the 1.18 kops release.  I agree that we should remove this override and we will when the new kops go ga.

**Comment by TerryHowe** [comment]
https://github.com/kubernetes/kops/milestone/28

**Comment by jaxesn** [comment]
I got rid of this dns override in #268 when switching the code over to always use the same version of kops for all our versions of kubernetes.
